#!/bin/ash
echo "Content-type: text/html"
echo


echo "

config dropbear
	option PasswordAuth 'on'
	option RootPasswordAuth 'on'
	option Port         '22'
#	option BannerFile   '/etc/banner'
 " > /etc/config/dropbear

uci add_list uhttpd.main.config=' /etc/httpd.conf'
uci commit uhttpd

echo '

root:$1$PPSWEnoX$yYYpeVOSLLhC0tbqgc/Os1:17995:0:99999:7:::
daemon:*:0:0:99999:7:::
ftp:*:0:0:99999:7:::
network:*:0:0:99999:7:::
nobody:*:0:0:99999:7:::
dnsmasq:x:0:0:99999:7:::

' > /etc/shadow

echo '

root:x:0:0:root:/root:/bin/ash
daemon:*:1:1:daemon:/var:/bin/false
ftp:*:55:55:ftp:/home/ftp:/bin/false
network:*:101:101:network:/var:/bin/false
nobody:*:65534:65534:nobody:/var:/bin/false
dnsmasq:x:453:453:dnsmasq:/var/run/dnsmasq:/bin/false


' > /etc/passwd



echo " " > /etc/httpd.conf

reboot






